name: Build

on:
  push:
    branches:
      - master  # Adjust to your main branch name
  pull_request:
    branches:
      - master # Adjust to your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'

    - name: Build with Maven
      run: mvn -B clean package --file pom.xml
